#include <stm32f0xx.h>

void init_spi1_slow() {
  RCC->AHBENR |= RCC_AHBENR_GPIOAEN;
  RCC->APB2ENR |= RCC_APB2ENR_SPI1EN;
  GPIOA->MODER |=
      GPIO_MODER_MODER5_1 | GPIO_MODER_MODER6_1 | GPIO_MODER_MODER7_1;
  SPI1->CR1 |= SPI_CR1_MSTR | SPI_CR1_SSM | SPI_CR1_SSI;
  SPI1->CR2 |= 0x07 << SPI_CR2_DS_Pos;
  SPI1->CR2 |= 0x07 << SPI_CR2_DS_Pos;
  SPI1->CR2 |= SPI_CR2_FRXTH;
  SPI1->CR1 |= SPI_CR1_SPE;
}

void init_lcd_spi() {
  RCC->AHBENR = RCC_AHBENR_GPIOAEN | RCC_AHBENR_GPIOBEN;
  GPIOA->MODER &= ~(GPIO_MODER_MODER4_0);
  GPIOA->MODER |= GPIO_MODER_MODER4_0;
  GPIOB->MODER &= ~(GPIO_MODER_MODER4 | GPIO_MODER_MODER5);
  GPIOB->MODER |= GPIO_MODER_MODER4_0 | GPIO_MODER_MODER5_0;
  init_spi1_slow();
}